version: '3.9'

services:
  redis:
    image: redis:alpine
    container_name: example-redis
    ports:
      - "6379:6379"
    networks:
      - worker-network

  worker:
    build: .
    container_name: example-worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - worker-network
    depends_on:
      - redis
  
networks:
  worker-network:
    driver: bridge
